# Generated by Django 5.2.7 on 2025-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysis',
            fields=[
                ('sha256_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'String Analysis',
                'verbose_name_plural': 'String Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
